project:
  type: book

book:
  title: "Operational Research Problems"
  author: "Troy Altus"
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/01-linear-programming.qmd
    - references.qmd

format:
  html:
    theme: cosmo
  pdf:
    documentclass: book

execute:
  cache: true
  engine: jupyter
