project:
  type: book

book:
  title: "Modern Operations Research with Python"
  subtitle: "Numerical Optimization, Machine Learning, and Data Analysis"
  author: "Troy"
  date: "today"
  chapters:
    - index.qmd
    - chapters/02-linear-programming.qmd
